#!/bin/bash
THE_DIR="/var/www/"

if [ ! -z "$1" ] 
	then
		THE_DIR="$1"
fi

echo "Updating ownership"
find $THE_DIR -not -iwholename '*.git*' -print0 | xargs -0 chown -h www-data:www-data
echo "Updating directories"
find $THE_DIR -type d -print0 | xargs -0 chmod -v 775
echo "Updating files"
find $THE_DIR -not -iwholename '*.git*' -type f -not -executable -print0 | xargs -0 chmod 664
echo "Done."