#!/bin/bash
THE_DIR="/var/www/"

if [ ! -z "$1" ] 
	then
		THE_DIR="$1"
fi

find $THE_DIR -print0 | xargs -0 chown -v -h www-data:www-data
find $THE_DIR -type d -print0 | xargs -0 chmod -v 775
find $THE_DIR -type f -not -executable -print0 | xargs -0 chmod -v 664
